Reduce TUI Installer flickering, network check (add SSL check)

diff --git a/tui-installer b/tui-installer
--- a/tui-installer
+++ b/tui-installer
@@ -18,7 +18,10 @@
 # Version of this script 
 # (For developer : Update whenever there is a change in this file or its related files)
 # format of Version Number is YYMMDDN which N is 1-99 count on updates commited on the same day)
-installerver=24030904
+installerver=24033101
+
+# required ACU version
+acuver="0.0.6-dev"
 
 # Define main / dev branch
 branch=dev
@@ -411,7 +414,8 @@ network_menu()
         fi
     done
 
-    last_check=$(date +%s)
+    local last_check=$(date +%s)
+    local last_internet
 
     while [[ "$ckin" != [wWsS] ]]; do
         read -t 0.1 -n 1 tmp && ckin=$tmp
@@ -443,7 +447,10 @@ network_menu()
             network_status="                    Waiting for Network ..."
         fi
         menu_option_title="\n\Z2$network_status\n\n\ZnEnter a key:\n\n"
-        info_alert "$menu_option_title w) Connect to a WiFi network ($wl_adapter) \n s) Skip Internet Check (Installation may fail)"
+        if [ $((current_time - last_check)) -ge 6 ] || [ "$last_internet" != "$internet_available" ]; then
+            info_alert "$menu_option_title w) Connect to a WiFi network ($wl_adapter) \n s) Skip Internet Check (Installation may fail)"
+            last_internet=$internet_available
+        fi
     done
     # Restore terminal settings
     clear
@@ -458,32 +465,58 @@ network_menu()
                 sudo wifi-menu $iwdev
             else
                 wifi-menu $iwdev
+                colorecho "$GREEN" "Enabling netctl Auto Connect ..."
+                systemctl enable netctl-auto@$iwdev.service
             fi               
-             # NTP Sync for WiFi
-                if ip link show | grep "state UP" | grep -q "wl" >/dev/null 2>&1; then
-                    colorecho "$GREEN" "Updating NTP Time Sync ..."
-                    if [ -x "$(command -v sudo)" ]; then
-                        sudo rm -rf /etc/systemd/network/*
-                        sudo systemctl restart systemd-networkd
-                        sleep 1
-                        sudo timedatectl set-ntp false
-                        sudo timedatectl set-ntp true
-                    else
-                        rm -rf /etc/systemd/network/*
-                        systemctl restart systemd-networkd
-                        sleep 1
-                        timedatectl set-ntp false
-                        timedatectl set-ntp true
-                    fi
-                fi
             ;;
     esac
+
+    # Loop until curl is successful or max attempts reached
+    attempt=0
+    until curl -sSf https://raw.githubusercontent.com/ >/dev/null 2>&1 || [ "$attempt" -ge 5 ]; do
+        colorecho "$RED" "Establishing SSL internet connection ..."
+        # NTP Sync
+        if [ "$attempt" -eq 1 ]; then
+            colorecho "$GREEN" "Updating NTP Time Sync ..."
+            if [ -x "$(command -v sudo)" ]; then
+                sudo rm -rf /etc/systemd/network/*
+                sudo systemctl restart systemd-networkd
+                sleep 1
+                sudo timedatectl set-ntp false
+                sudo timedatectl set-ntp true
+            else
+                rm -rf /etc/systemd/network/*
+                systemctl restart systemd-networkd
+                sleep 1
+                timedatectl set-ntp false
+                timedatectl set-ntp true
+            fi
+        fi
+        sleep 5
+        ((attempt++))
+    done
+
+    if [ "$attempt" -ge 5 ]; then
+        systemctl status systemd-timesyncd # for debugging
+        colorecho "$RED" "Failed to establish SSL internet connection after $attempt attempts."
+        colorecho "$YELLOW" "Restart your device and try again or press Ctrl+C to exit this installer for manual operation."
+        options=("Continue Anyway (may break)" "Restart Now")
+        select_option "${options[@]}"
+        answer=$?
+        if [ "$answer" = 1 ]; then
+            colorecho "$GREEN" "System will reboot now."
+            if ! reboot --force; then
+                echo "Unable to reboot automatically, please reboot your device manually."
+            fi
+        fi
+    fi
 }
 
 # Check Installer Updates
 check_installer_updates() {
     colorecho "$YELLOW" "Checking for installer updates..."
     remote_installerver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tools/tui-installer" | grep -o 'installerver=[0-9]*' | cut -d= -f2)
+    remote_acuver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tools/tui-installer" | grep -o 'acuver=[0-9]*' | cut -d= -f2) #TODO
     if [ "$remote_installerver" -gt "$installerver" ]; then
         menu_header="Installer Updates Available"
         menu_option_title="\Z2A newer version ($remote_installerver) of this installer is available, do you want to update this installer?\Zn"
@@ -529,6 +562,7 @@ check_installer_updates() {
 installer_menu() {
 
     # Choose Language
+    lclist=$(acu locale list-available)
     menu_header="Language"
     menu_option_title="\Zb          Let's begin with setting up your language, is that right?\Zn\n\nSuggested Languages:"
     options=("English (Canada)" "French (Canada)" "More Languages")
