Enable TUI Installer updates

diff --git a/tui-installer b/tui-installer
--- a/tui-installer
+++ b/tui-installer
@@ -18,10 +18,10 @@
 # Version of this script 
 # (For developer : Update whenever there is a change in this file or its related files)
 # format of Version Number is YYMMDDN which N is 1-99 count on updates commited on the same day)
-installerver=24041101
+installerver=24041102
 
 # required ACU version
-acuver="0.0.6-dev"
+acuver=0.0.6-dev
 
 # Define main / dev branch
 branch=dev
@@ -585,44 +585,35 @@ network_menu()
 # Check Installer Updates
 check_installer_updates() {
     colorecho "$YELLOW" "Checking for installer updates..."
-    remote_installerver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tools/tui-installer" | grep -o 'installerver=[0-9]*' | cut -d= -f2)
-    remote_acuver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tools/tui-installer" | grep -o 'acuver=[0-9]*' | cut -d= -f2) #TODO
+    remote_installerver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tui-installer" | grep -o 'installerver=[0-9]*' | cut -d= -f2)
+    remote_acuver=$(curl -s "https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tui-installer" | grep -o 'acuver=[0-9]*' | cut -d= -f2) #TODO
     if [ "$remote_installerver" -gt "$installerver" ]; then
         menu_header="Installer Updates Available"
-        menu_option_title="\Z2A newer version ($remote_installerver) of this installer is available, do you want to update this installer?\Zn"
+        menu_option_title="\Z2A newer version ($remote_installerver) of this installer is available. \n\Zn Do you want to update this installer?"
         options=("Update this Installer" "Do not update this installer")
         select_option "${options[@]}"
         answer=$?
         if [ "$answer" = 0 ]; then
             # Download Installer
             colorecho "$GREEN" "Downloading Installer ..."
-            exit 1 #THIS PREVENTS AN UPDATE #ONLY USED TO PREVENT DATA LOSS IN DEVELOPMENT
-            curl -LJO https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tools/tui-installer
+            #exit 1 #THIS PREVENTS AN UPDATE #ONLY USED TO PREVENT DATA LOSS IN DEVELOPMENT
+            curl -LJO https://raw.githubusercontent.com/kwankiu/archlinux-installer-rock5/$branch/tui-installer
 
             # Update tui-installer
             colorecho "$GREEN" "Updating Installer ..."
-            # Check if the script is being run with root privileges
-            if [ $(id -u) -eq 0 ]; then
-                # If running as root
-                sed -i "s/install_target=\"rock5\"/install_target=\"$install_target\"/g" tui-installer
-                chmod +x tui-installer
-                cp -r tui-installer /usr/bin/installer
-                rm -rf tui-installer
-                colorecho "$GREEN" "Installer updated. System will reboot now."
-                if ! reboot --force; then
-                    echo "Unable to reboot automatically, please reboot your device manually."
-                fi
-            else
-                # If not running as root
-                sudo sed -i "s/install_target=\"rock5\"/install_target=\"$install_target\"/g" tui-installer
-                sudo chmod +x tui-installer
-                sudo cp -r tui-installer /usr/bin/installer
-                sudo rm -rf tui-installer
-                colorecho "$GREEN" "Installer updated. System will reboot now."
-                if ! sudo reboot; then
-                    echo "Unable to reboot automatically, please reboot your device manually."
-                fi
+            sudo sed -i "s/install_target=\"rock5\"/install_target=\"$install_target\"/g" tui-installer
+            sudo chmod +x tui-installer
+            sudo cp -r tui-installer /usr/bin/installer
+            sudo rm -rf tui-installer
+            colorecho "$GREEN" "Installer updated. System will reboot now."
+            if ! sudo reboot --force; then
+                echo "Unable to reboot automatically, please reboot your device manually."
             fi
+
+            # Update ACU
+            echo "Updating ACU (Configuration Utility) ..."
+            curl -o /usr/bin/acu -L "https://raw.githubusercontent.com/kwankiu/acu/$remote_acuver/acu"
+            chmod +x /usr/bin/acu
         fi
     fi
 }
